; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26732.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Анюта\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
